import inngest

from app.inngest.client import inngest_client
from app.services import embeddings, github, llm, vectordb
from app.services.frontend import fetch_custom_rules, log_pr_creation


@inngest_client.create_function(
    fn_id="handle_auto_pr", trigger=inngest.TriggerEvent(event="issue/auto-pr")
)
async def handle_auto_pr(ctx: inngest.Context):
    data = ctx.event.data
    installation_id = data["installation_id"]
    owner = data["owner"]
    repo_name = data["repo_name"]
    issue_number = data["issue_number"]
    issue_title = data["issue_title"]
    issue_body = data["issue_body"]
    repo_full_name = f"{owner}/{repo_name}"

    token = await github.get_installation_token(installation_id)

    query = f"{issue_title}\n{issue_body}"
    related_code = ""
    file_paths = set()

    query_embedding = await embeddings.create_embedding(query[:8000])
    search_results = await vectordb.search(
        query_embedding, limit=10, repo=repo_full_name
    )

    for point in search_results:
        payload = point.payload
        path = payload.get("path", "")
        if path:
            file_paths.add(path)
            content = payload.get("content", "")
            name = payload.get("name", "")
            chunk_type = payload.get("chunk_type", "code")
            header = f"File: {path}"
            if name:
                header += f" | {chunk_type}: {name}"
            related_code += f"\n-- {header} ---\n{content}\n"

    file_contents = {}
    file_shas = {}

    for path in list(file_paths):
        file_data = await github.get_file_content(owner, repo_name, path, token)
        file_contents[path] = file_data["content"]
        file_shas[path] = file_data["sha"]

    custom_rules = await fetch_custom_rules(installation_id)

    plan = await llm.plan_issue_fix(
        issue_title=issue_title,
        issue_body=issue_body,
        related_code=related_code,
        file_contents=file_contents,
        custom_rules=custom_rules,
    )

    changes = []
    for file_plan in plan["files"]:
        file_path = file_plan["path"]
        action = file_plan["action"]
        description = file_plan["description"]

        current_content = file_contents.get(file_path)

        if action == "modify" and not current_content:
            file_data = await github.get_file_content(
                owner, repo_name, file_path, token
            )
            current_content = file_data["content"]
            file_shas[file_path] = file_data["sha"]

        new_content = await llm.generate_file_change(
            file_path=file_path,
            current_content=current_content,
            action=action,
            change_description=description,
            issue_title=issue_title,
            issue_body=issue_body,
            custom_rules=custom_rules,
        )

        changes.append(
            {
                "path": file_path,
                "action": action,
                "content": new_content,
                "sha": file_shas.get(file_path),
            }
        )

    branch_name = f"PRSense/issue-{issue_number}"
    default_branch = await github.get_default_branch(owner, repo_name, token)
    await github.create_branch(owner, repo_name, branch_name, default_branch, token)

    for change in changes:
        if change["action"] == "delete":
            await github.delete_file(
                owner,
                repo_name,
                change["path"],
                f"chore: delete {change['path']} for issue #{issue_number}",
                branch_name,
                change["sha"],
                token,
            )
        else:
            await github.create_or_update_file(
                owner,
                repo_name,
                change["path"],
                change["content"],
                f"chore: update {change['path']} for issue #{issue_number}",
                branch_name,
                token,
                change.get("sha"),
            )

    pr_body = f"""## Summary
{plan.get("summary", "Automated fix for the issue.")}

Closes #{issue_number}

## Changes
{chr(10).join([f"- `{c['path']}` ({c['action']})" for c in changes])}

## Approach
{plan.get("approach", "N/A")}

---
*This PR was automatically generated by PRSense from issue #{issue_number}*
"""
    pr = await github.create_pull_request(
        owner,
        repo_name,
        title=f"Fix: {issue_title}",
        body=pr_body,
        head=branch_name,
        base=default_branch,
        token=token,
    )
    pr_number = pr["number"]
    pr_url = pr["html_url"]
    pr_github_id = pr.get("id", 0)

    await log_pr_creation(
        repo_full_name, pr_number, f"Fix: {issue_title}", pr_github_id, issue_number
    )

    success_comment = f"I've created a PR to fix this issue: #{pr_number}\n\n{pr_url}"
    await github.post_comment(owner, repo_name, issue_number, success_comment, token)